<a href="https://colab.research.google.com/github/soumyadweep/CodeClauseInternship_Loan-Prediction-Project-using-ML-in-Python/blob/main/LoanPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
import pandas as pd

In [39]:
loan_train = pd.read_csv('train_csv.csv')

In [40]:
loan_train.shape

(614, 13)

In [41]:
loan_train.sample(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
16,LP001034,Male,No,1,Not Graduate,No,3596,0.0,100.0,240.0,NaN,Urban,Y
278,LP001907,Male,Yes,0,Graduate,No,14583,0.0,436.0,360.0,1.0,Semiurban,Y
188,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y
603,LP002958,Male,No,0,Graduate,No,3676,4301.0,172.0,360.0,1.0,Rural,Y
342,LP002119,Male,Yes,1,Not Graduate,No,4554,1229.0,158.0,360.0,1.0,Urban,Y
595,LP002940,Male,No,0,Not Graduate,No,3833,0.0,110.0,360.0,1.0,Rural,Y
587,LP002917,Female,No,0,Not Graduate,No,2165,0.0,70.0,360.0,1.0,Semiurban,Y
301,LP001972,Male,Yes,NaN,Not Graduate,No,2875,1750.0,105.0,360.0,1.0,Semiurban,Y
472,LP002519,Male,Yes,3+,Graduate,No,4691,0.0,100.0,360.0,1.0,Semiurban,Y
65,LP001225,Male,Yes,0,Graduate,No,5726,4595.0,258.0,360.0,1.0,Semiurban,N

In [42]:
loan_train.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [43]:
loan_train['Gender'] = loan_train['Gender'].fillna(loan_train['Gender'].dropna().mode().values[0])
loan_train['Married'] = loan_train['Married'].fillna(loan_train['Married'].dropna().mode().values[0])
loan_train['Dependents'] = loan_train['Dependents'].fillna(loan_train['Dependents'].dropna().mode().values[0])
loan_train['Self_Employed'] = loan_train['Self_Employed'].fillna(loan_train['Self_Employed'].dropna().mode().values[0])
loan_train['LoanAmount'] = loan_train['LoanAmount'].fillna(loan_train['LoanAmount'].dropna().mode().values[0])
loan_train['Loan_Amount_Term'] = loan_train['Loan_Amount_Term'].fillna(loan_train['Loan_Amount_Term'].dropna().mode().values[0])
loan_train['Credit_History'] = loan_train['Credit_History'].fillna(loan_train['Credit_History'].dropna().mode().values[0])

In [44]:
loan_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             614 non-null    object
 2   Married            614 non-null    object
 3   Dependents         614 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      614 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [45]:
print(set(loan_train['Gender'].values.tolist()))
print(set(loan_train['Married'].values.tolist()))
print(set(loan_train['Dependents'].values.tolist()))
print(set(loan_train['Self_Employed'].values.tolist()))
print(set(loan_train['Education'].values.tolist()))
print(set(loan_train['Loan_Status'].values.tolist()))
print(set(loan_train['Property_Area'].values.tolist()))

{'Male', 'Female'}
{'No', 'Yes'}
{'3+', '0', '2', '1'}
{'No', 'Yes'}
{'Not Graduate', 'Graduate'}
{'Y', 'N'}
{'Rural', 'Semiurban', 'Urban'}

In [46]:
from sklearn.preprocessing import StandardScaler
loan_train['Loan_Status'] = loan_train['Loan_Status'].map({'Y':1,'N':0}).astype('Int64')
loan_train= pd.get_dummies(loan_train,columns = ['Gender','Dependents','Married','Self_Employed','Education','Property_Area'])
standardscaler = StandardScaler()
columns_to_normalize = ['ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term',]
loan_train[columns_to_normalize] = standardscaler.fit_transform(loan_train[columns_to_normalize])

In [47]:
loan_train.head()

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Female,Gender_Male,Dependents_0,...,Dependents_3+,Married_No,Married_Yes,Self_Employed_No,Self_Employed_Yes,Education_Graduate,Education_Not Graduate,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,0.072991,-0.554487,-0.302759,0.273231,1.0,1,0,1,1,...,0,1,0,1,0,1,0,0,0,1
1,LP001003,-0.134412,-0.038732,-0.207648,0.273231,1.0,0,0,1,0,...,0,0,1,1,0,1,0,1,0,0
2,LP001005,-0.393747,-0.554487,-0.944757,0.273231,1.0,1,0,1,1,...,0,0,1,0,1,1,0,0,0,1
3,LP001006,-0.462062,0.251980,-0.302759,0.273231,1.0,1,0,1,1,...,0,0,1,1,0,0,1,0,0,1
4,LP001008,0.097728,-0.554487,-0.053093,0.273231,1.0,1,0,1,1,...,0,1,0,1,0,1,0,0,0,1

In [48]:
from sklearn.model_selection import train_test_split
y = loan_train['Loan_Status']
x = loan_train.drop(['Loan_ID','Loan_Status'],axis = 1)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 42)

##XGBoost

In [49]:
from sklearn import metrics
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, RandomizedSearchCV

In [50]:
gbm_param_grid = {
    'n_estimators':range(1,1000,10),
    'max_depth':range(1,20),
    'learning_rate':[.1,.4,.45,.5,.55,.6],
    'colsample_bytree':[.6,.7,.8,.9,1],
}
xgb_classifier = XGBClassifier()
xgb_random = RandomizedSearchCV(param_distributions = gbm_param_grid,estimator = xgb_classifier,scoring = "accuracy",verbose = 0,n_iter = 100,cv=4)
xgb_random.fit(x_train,y_train)
print(f'Best Parameters:{xgb_random.best_params_}')

y_pred = xgb_random.predict(x_test)
print(f'Accuracy:{np.sum(y_pred==y_test)/len(y_test)}')

Best Parameters:{'n_estimators': 231, 'max_depth': 1, 'learning_rate': 0.1, 'colsample_bytree': 0.7}
Accuracy:0.7886178861788617

In [54]:
from sklearn.metrics import accuracy_score

# Assuming you have the true target values (y_true) and predicted values (y_pred)
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.79

In [55]:
from sklearn.metrics import precision_score, recall_score

# Assuming you have the true target values (y_true) and predicted values (y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

# Print the precision and recall
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')

Precision: 0.76
Recall: 0.99